### ISSUE TITLE
Text Editing Functionality

### ISSUE THREAD

**Issue by quadrophobiac** [theodi/edward-csvhands#17]
As a desktop editing software user
I want to be able to 
[ ] add new rows  
[ ] add new columns  
[ ] rename headers
[ ] enter text into rows and columns

**Comment by quadrophobiac** [comment]
@quadrophobiac - add new rows  
- right click and select enter new row

@bcouston - add new columns
- right click and select enter new column
@danielgavrilov - rename headers

write the tests first! involves accessing the handsontable api

**Comment by bcouston** [comment]
I'll take new columns

**Comment by bcouston** [comment]
All handled and tested by handsontable
