### ISSUE TITLE
Validate CSV

### ISSUE THREAD

**Issue by pezholio** [theodi/edward-csvhands#2]
As a CSV editor
I want to run a validation against CSVlint
So I can improve the quality of my data

**Comment by pezholio** [comment]
CSVlint API is validated here:

https://github.com/theodi/csvlint/wiki/Webservice

Suggest we create a [Data URI](https://en.wikipedia.org/wiki/Data_URI_scheme) from the file contents and create a validation that way. I *think* that's how file uploads work

**Comment by bcouston** [comment]
Sub-tasks:

- Send file for validation
- Wait for validation
- Handle validation results
- Display in pane

**Comment by bcouston** [comment]
Also:

- Implement fail condition in file stream
