### ISSUE TITLE
Schema Editor (JSON) Support

### ISSUE THREAD

**Issue by quadrophobiac** [theodi/edward-csvhands#20]
As a CSV schema checker, 
I would like GUI support for multi file editor screens, 
Including a pane to show an inline schema formatted to detect JSON

**Comment by pezholio** [comment]
I think it's better to keep the JSON invisible to the end user. Implement an option in Tools > Define header.

This would then add a popup window with each column defined. The user can then add a [field type](http://dataprotocols.org/json-table-schema/#field-types-and-formats) and [constraints](http://dataprotocols.org/json-table-schema/#field-constraints) for each field.

**Comment by quadrophobiac** [comment]
progress made towards opening two different file types exist in this branch, which will not be a PR - https://github.com/theodi/edward-csvhands/tree/open-different-file-types, instead I will pull the changed files within this to a new branch from master (once https://github.com/theodi/edward-csvhands/pull/36 is complete, as the changes made to package generation overlap with the outputted file functionality) in issue 'header-wizard'
