### ISSUE TITLE
Highlight invalid rows and columns

### ISSUE THREAD

**Issue by pezholio** [theodi/edward-csvhands#4]
As a CSV editor
I want invalid rows and columns to be highlighted
So I can easily see what needs correcting

**Comment by pezholio** [comment]
This could include showing the exact error when hovering over rows / columns

**Comment by bcouston** [comment]
Suggestion to change it to highlight where the errors are when hovering over the specific validation message rather than the table. Otherwise I think it could be quite a coloury clutery mess.

**Comment by bcouston** [comment]
Would be useful if it could jump to the relevant row where the validation message is happening if it is a large file.

**Comment by quadrophobiac** [comment]
some amazing test fodder here http://csvlint.io/validation/55cc851163737608aa000015
